Fix 6654
oneconvergence/dkube pull request #49
Opened 2021-04-22 16:48 UTC by pallavi-pannu-oc

2021-04-23 01:38 UTC, hemanthravi commented
@pallavi-pannu-oc 
Does the fix work when models are deployed from Model Repo directly and not from Model Catalog.

2021-04-23 04:01 UTC, riteshkarvaloc requested changes
@pallavi-pannu-oc can you also add a parameter for `modelcatlog` name as in `get_modelcatalog_item` such that the user can provide any of it. 

Also, add the information about this parameter as added for others.

2021-04-23 17:35 UTC, songole commented
Did you make sure the change doesn't break 2.1?

2021-04-26 05:04 UTC, riteshkarvaloc approved these changes

2021-04-26 15:31 UTC, merged

2021-04-26 20:44 UTC, hemanthravi commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
@riteshkarvaloc 
This might break backward compat. Might need to be changed to
create_model_delpoyment(self, user, model, version, modelcatalog=None, .....)

2021-04-27 02:08 UTC, riteshkarvaloc commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
@hemanthravi @deepio-oc @songole the issue is that the earlier version of this function expects model_catlog name in the `model` argument. 
`def create_model_deployment(self, user, name, model="published/catlog name", version='12234567')`

Even with the change `create_model_delpoyment(self, user, model, version, modelcatalog=None, .....)`  the old programs will not work because those programs will be passing model catalog name to the model argument. but the doc says the name of the model to be deployed https://dkube.io/dkube-sdk2.2/index.html#dkube.sdk.api.DkubeApi.create_model_deployment, which was creating confusion. @deepio-oc  @songole if we agree to pass the model catalog name to the model argument, these changes can be reverted back.

2021-04-27 02:40 UTC, deepio-oc commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
yes, we can pass model catalog name as the argument and revert these changes.

2021-04-27 03:56 UTC, riteshkarvaloc commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
@deepio-oc can we go with this `create_model_delpoyment(self, user, model, modelrepo=None, version, .....)`? or only `def create_model_deployment(self, user, name, model="published/catlog name", version='12234567')`

2021-04-27 15:57 UTC, deepio-oc commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
`def create_model_deployment(self, user, name, model="published/catlog name", version='12234567')`

This better matches with the UI flow where we select a model catalog entry and click deploy.

2021-04-27 16:00 UTC, riteshkarvaloc commented on dkube/sdk/api.py
> +    def create_model_deployment(self, user, name, model=None, modelcatalog=None, version=None,
@deepio-oc it's done in the PR https://github.com/oneconvergence/dkube/pull/52. Kindly review it.