Feature store v2
oneconvergence/dkube pull request #6
Opened 2020-11-05 14:15 UTC by riteshkarvaloc

Feature store revised.

2020-11-06 06:37 UTC, songole requested changes

2020-11-06 06:37 UTC, songole commented on dkube/sdk/rsrcs/featureStore.py
> +            table = pq.read_table(os.path.join(path, 'example.parquet'))
Can we use a better name. featureset.parquet?

2020-11-06 06:37 UTC, songole commented on dkube/sdk/rsrcs/featureStore.py
> +        response = api.featureset_commit_version(featureset, path)
You need to pass job id. Take a look at the swagger.yaml for signature. You can also get job id from the environment variable.

perhaps, we should just make commit API to commit all output featuresets. I will talk to @ajayanto. In which case, we don't need featureset name

2020-11-06 06:47 UTC, songole commented on dkube/sdk/rsrcs/featureStore.py
> +
Is there a reason why all this is here?

2020-11-06 06:50 UTC, songole commented on dkube/sdk/rsrcs/featureStore.py
> -                            "s3", "gcs", "nfs", "redshift", "k8svolume"]
I am not sure what this is?

2020-11-06 06:50 UTC, songole commented on dkube/sdk/rsrcs/featureStore.py
> -            return return {"data": df_empty, "status": -1, "error": "Path of featureset not found"}
Removed all APIs? Are you moving them somewhere?

2020-11-09 17:31 UTC, mak-454 commented on dkube/sdk/api.py
> +                    path = each_feature["location"]
if feature matches here.. should there be a break in loop? or the below if condition needs to move in?

2020-11-09 17:33 UTC, mak-454 commented on dkube/sdk/api.py
> +    def commit_featureset(self, jobid, featuresset, path):
@riteshkarvaloc what is jobid here? user will not know right... u may need to take jobname here... dont u need user?

2020-11-09 18:08 UTC, mak-454 commented on dkube/sdk/api.py
> +            featureset) == DkubeFeatureSet, "Invalid type for run, value must be instance of rsrcs:DkubeDataset class"
error message is wrong.. it should be "Invalid type for run, value must be instance of rsrcs:Featureset class"

2020-11-09 18:08 UTC, mak-454 commented on dkube/sdk/api.py
> +                    "dataset {} - completed with state {} and reason {}".format(featureset.name, state, reason))
not dataset... but featureset

2020-11-09 18:08 UTC, mak-454 commented on dkube/sdk/api.py
> +                    "dataset {} - completed with state {} and reason {}".format(featureset.name, state, reason))
can you correct @ other places too

2020-11-09 18:10 UTC, mak-454 commented on dkube/sdk/api.py
> +        if path is None and self.CONFIG_FILE is None:
why to use self.CONFIG_FILE ?? This class should be stateless... it may be possible that user uses single object of this class for multiple apis.. can you not make this class contextual.. take whatever is needed as arguments

2020-11-10 16:41 UTC, riteshkarvaloc commented on dkube/sdk/api.py
> +                    path = each_feature["location"]
the loop will break after finishing all the mounted featuresets.

2020-11-11 00:23 UTC, songole requested changes

2020-11-11 00:23 UTC, songole commented on dkube/sdk/api.py
> +    def commit_featureset(self, featuresset, path):
commit api doesn't take any parameters. It commits all dirty featuresets that are specified in the outputs section of a job. Please look at the swagger definition

2020-11-11 00:23 UTC, songole commented on dkube/sdk/rsrcs/featureSet.py
> +        self.datum = DatumModel(name=None, tags=None, _class='featureset',
featureset has nothing to do with DatumModel 
it should be self.featureset = FeaturesetDef(....)
this is defined in dkube/sdk/internal/dkube_api/models/feature_set_def.py

2020-11-11 00:23 UTC, songole commented on dkube/sdk/rsrcs/featureSet.py
> +    FEATURE_SOURCES = ["dvs", None]
we don't need this.

2020-11-16 05:42 UTC, mak-454 commented on dkube/sdk/api.py
> +            self.files_url = os.getenv(
why do we need this? when it is same as self.url ?

2020-11-16 05:43 UTC, mak-454 commented on dkube/sdk/api.py
> +        if path is None and self.CONFIG_FILE is None:
can we remove self.CONFIG_FILE ?

2020-11-16 05:44 UTC, mak-454 commented on dkube/sdk/api.py
> +        if path is None and self.CONFIG_FILE is None:
Is there no featureset file in internal/rsrcs... this kind of logic should move there...

2020-11-16 05:44 UTC, mak-454 commented on dkube/sdk/api.py
> +            return {"status": -1, "error": "Featureset doesn't exist"}
can this move in rsrcs/featureset.py ?

2020-11-16 05:46 UTC, mak-454 commented on dkube/sdk/api.py
> +class DkubeApi(ApiBase, FilesBase):
@riteshkarvaloc I dont see this FilesBase? what would be the purpose of this class?

2020-11-16 05:48 UTC, songole commented on dkube/sdk/api.py
> +            self.files_url = os.getenv(
Internal service name is different for controller and downloader. External URL is the same.

2020-11-16 05:50 UTC, mak-454 commented on dkube/sdk/api.py
> +class DkubeApi(ApiBase, FilesBase):
i see

2020-11-16 05:50 UTC, songole commented on dkube/sdk/api.py
> +class DkubeApi(ApiBase, FilesBase):
Features metadata is uploaded as a file. Today, fileupload goes through a different interface. There is files_base.py

2020-11-16 10:21 UTC, riteshkarvaloc commented on dkube/sdk/api.py
> +            return {"status": -1, "error": "Featureset doesn't exist"}
the path search logic is moved to the featureset.py

2020-11-25 04:40 UTC, closed without merging